### ISSUE TITLE
Parsing error on missing response body

### ISSUE THREAD

**Issue by jans510** [zalando-incubator/perron#27]
If a request returns no response body (for example a gateway timeout 504), perron produces  parsing errors as it tries to parse an empty body. This leads to an obfuscation of the original error.

![parsingerror](https://user-images.githubusercontent.com/12793206/28606528-c487df6a-71d7-11e7-97fc-eabde0d27f68.png)

![parsingerror1](https://user-images.githubusercontent.com/12793206/28606544-d6fcc98a-71d7-11e7-84b2-cbda4198597a.png)

![parsingerror2](https://user-images.githubusercontent.com/12793206/28606547-dbcb3488-71d7-11e7-8503-8fe52749deda.png)

I think in case that no response body is provided, perron should not try to parse it but return the statusCode and headers without throwing an exception..

**Comment by jans510** [comment]
I've seen that it is already fixed in the newest version, so close the tissue.

**Comment by shuhei** [comment]
Yeah, it will still happen if API server responds with `Content-Type: application/json` and an empty body. But in that case, I think the API server shouldn't respond with an empty body...
